spring.application.name=EmailSpringBoot

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=injac.mladen@gmail.com
spring.mail.password= ylzddylzddsedafrebzemsedafrebzem

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true